version : "3"
services:
  app:
    container_name:
    #set container_name
    restart: always
    build: .
    ports:
      - "8080:8080"
    networks:
      - nginx


networks:
          nginx:
              external: true
